<div id="footer">
  <div class="links">
    <p>
      Copyright&copy; opencomUS All Rights Reserved.
      <br />
      848 N. Rainbow Blvd. #2971 Las Vegas, NV 89107
      <br /><br />
      <!--onclick="OpenUrl(this.href,'PrivacyPolicy');return false;"-->
      <a href="http://vipcashfast.com/Privacy.Policy.aspx">Privacy Policy</a>
      &nbsp;&nbsp;
      <!--onclick="OpenUrl(this.href,'TermsandConditions');return false;"-->
      <a href="http://vipcashfast.com/Terms.Conditions.aspx">Terms and Conditions</a>
      &nbsp;&nbsp;
      <a href="http://vipcashfast.com/Contact.aspx">Contact</a>
    </p>

    <p>
      <span id="siteseal">
        <script type="text/javascript" src="https://seal.starfieldtech.com/getSeal?sealID=YbvWTadogOEGVG5qmmzDM2zkgA5FqH5X7KYNAKiBy3P69aiX82NqXzn8Tkee"></script><br/><a style="font-family: arial; font-size: 9px" href="http://www.starfieldtech.com" target="_blank">SSL Certificate</a>
      </span>
    </p>
  </div>
    <div>
    <p style="text-align: left; margin: 25px 100px 0px 100px">
      <font class="white10">
          opencomUS offers this internet based <a class="white10" href="http://cashadvances.vipcashfast.com" >cash advance</a>,
          <a class="white10" href="http://paydayloans.vipcashfast.com">payday loan</a> marketing service to
          match you with the <a class="white10" href="http://cashadvances.vipcashfast.com">cash advance</a>,
          <a class="white10" href="http://paydayloans.vipcashfast.com">payday loan</a> service that can best
          help you make it to your next paycheck. This advertisement is an invitation to complete a loan
          application for a <a class="white10" href="http://cashadvances.vipcashfast.com">cash advance</a>
          or <a class="white10" href="http://paydayloans.vipcashfast.com">payday loan</a> and not an offer
          to make a loan. <a class="white10" href="http://vipcashfast.com">vipcashfast.com</a> is not a lender and does not make loans or credit
          decisions nor acts as a representative, agent, or correspondent for any service
          provider or lender. <a class="white10" href="http://vipcashfast.com">vipcashfast.com</a> does not charge any fees for the matching service
          or make any guarantee your application will be matched with a service provider or
          lender. This <a class="white10" href="http://cashadvances.vipcashfast.com">cash advance</a> or <a
          class="white10" href="http://paydayloans.vipcashfast.com">payday loan</a> offer may or may not
          be available in your state. The law of the state chosen by your final lender shall
          govern the <a class="white10" href="http://cashadvances.vipcashfast.com">cash advance</a>,
          <a class="white10" href="http://paydayloans.vipcashfast.com">payday loan</a> transaction.
      </font>
        
        <font class="g10-plain">
        <br/><a href="http://www.activesearchresults.com" class="g10-plain" target='_blank'>ASR Search Engine</a>&nbsp;<a href='http://www.apexoo.com/directory/Business/Financial_Services/Loans/' target='_blank' class="g10-plain">Apexoo Loan Directory</a>
        </font>
    </p>
    
    
  </div>
</div>